//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HashPassword.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assets()
        {
            this.Contracts = new HashSet<Contracts>();
            this.Maintenance = new HashSet<Maintenance>();
        }
    
        public int Id { get; set; }
        public string AssetName { get; set; }
        public int TypeId { get; set; }
        public string InventoryNumber { get; set; }
        public decimal InitialCost { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public int StatusId { get; set; }
    
        public virtual AssetStatuses AssetStatuses { get; set; }
        public virtual AssetTypes AssetTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contracts> Contracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance> Maintenance { get; set; }
    }
}
