//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HashPassword.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contracts()
        {
            this.PaymentSchedule = new HashSet<PaymentSchedule>();
            this.Reports = new HashSet<Reports>();
        }
    
        public int Id { get; set; }
        public string ContractNumber { get; set; }
        public int LesseeId { get; set; }
        public int AssetId { get; set; }
        public int ManagerId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal MonthlyPayment { get; set; }
        public Nullable<decimal> BuyoutPrice { get; set; }
        public int StatusId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Assets Assets { get; set; }
        public virtual ContractStatuses ContractStatuses { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Lessees Lessees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentSchedule> PaymentSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reports> Reports { get; set; }
    }
}
