//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HashPassword.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        public int Id { get; set; }
        public int AssetId { get; set; }
        public System.DateTime MaintenanceDate { get; set; }
        public int TypeId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Assets Assets { get; set; }
        public virtual MaintenanceTypes MaintenanceTypes { get; set; }
    }
}
