//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HashPassword.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int Id { get; set; }
        public int ScheduleId { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal AmountPaid { get; set; }
        public int MethodId { get; set; }
        public int StatusId { get; set; }
    
        public virtual PaymentMethods PaymentMethods { get; set; }
        public virtual PaymentSchedule PaymentSchedule { get; set; }
        public virtual PaymentStatuses PaymentStatuses { get; set; }
    }
}
