//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HashPassword.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int Id { get; set; }
        public int TypeId { get; set; }
        public System.DateTime Period { get; set; }
        public System.DateTime SubmissionDate { get; set; }
        public string Authority { get; set; }
        public int EmployeeId { get; set; }
        public int ContractId { get; set; }
    
        public virtual Contracts Contracts { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual ReportTypes ReportTypes { get; set; }
    }
}
